In [2]:
import numpy as np
t1 = np.array([1,2,3,])
t1

array([1, 2, 3])

In [3]:
type(t1)

numpy.ndarray

In [4]:
t2 = np.array(range(10))
t2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.array(range())` 等价于 `np.arange()`

In [5]:
t3 = np.arange(10)
t3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
t3.dtype

dtype('int32')

## 数组类型的操作

In [7]:
t4 = np.array(range(1,4), dtype=float)
t4

array([1., 2., 3.])

In [8]:
t4.dtype

dtype('float64')

In [10]:
t4 = np.array(range(1,4), dtype='i1')
t4.dtype

dtype('int8')

In [14]:
t5 = np.array([1,1,0,1,0,0], dtype=bool)
t5

array([ True,  True, False,  True, False, False])

In [31]:
t5.dtype

dtype('int8')

In [32]:
t6 = t5.astype('int8')
t6

array([1, 1, 0, 1, 0, 0], dtype=int8)

In [33]:
t6.dtype

dtype('int8')

In [64]:
import random
t7 = np.array([random.random() for i in range(10)])
t7

array([0.83585706, 0.95197944, 0.28592678, 0.52585343, 0.99736327,
       0.69253251, 0.72366104, 0.37327537, 0.06867872, 0.4564642 ])

In [65]:
t7.dtype

dtype('float64')

In [68]:
t8 = np.round(t7, 2)
t8

array([0.84, 0.95, 0.29, 0.53, 1.  , 0.69, 0.72, 0.37, 0.07, 0.46])

# 数组的维度

In [70]:
t1 = np.arange(12)
t1.shape

(12,)

In [72]:
t2 = np.array([[1,2,3],
               [4,5,6]])
t2.shape

(2, 3)

In [76]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
t3.shape

(2, 2, 3)

In [97]:
t4 = np.arange(12)
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
t4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
t5 = np.arange(24).reshape((2,3,4))
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [108]:
t5 = t5.reshape(4,6)

In [109]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [110]:
t5.reshape((24,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [111]:
t5.reshape((1,24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [112]:
t6 = t5.reshape((t5.shape[0]*t5.shape[1],))
t6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

维度展开

In [117]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [116]:
t5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 广播机制

In [118]:
t5 + 2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [119]:
t5 / 0

C:\Users\zhao\AppData\Local\Temp\ipykernel_11432\265377603.py:1: RuntimeWarning: divide by zero encountered in true_divide
  t5 / 0
C:\Users\zhao\AppData\Local\Temp\ipykernel_11432\265377603.py:1: RuntimeWarning: invalid value encountered in true_divide
  t5 / 0


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [120]:
t6 = np.arange(100,124).reshape((4,6))

对应位置数值进行计算

In [121]:
t6+t5

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [122]:
t7 = np.arange(0,6)

每一行减去被减数组

In [123]:
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [124]:
t8 = np.arange(4).reshape(4,1)

每一列减去被减列

In [125]:
t5-t8

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [126]:
t9 = np.arange(10)

In [127]:
t5-t9

ValueError: operands could not be broadcast together with shapes (4,6) (10,) 

## 轴