In [1]:
import numpy as np
t1 = np.array([1,2,3,])
t1

array([1, 2, 3])

In [2]:
type(t1)

numpy.ndarray

In [3]:
t2 = np.array(range(10))
t2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.array(range())` 等价于 `np.arange()`

In [4]:
t3 = np.arange(10)
t3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
t3.dtype

dtype('int64')

## 数组类型的操作

In [6]:
t4 = np.array(range(1,4), dtype=float)
t4

array([1., 2., 3.])

In [7]:
t4.dtype

dtype('float64')

In [8]:
t4 = np.array(range(1,4), dtype='i1')
t4.dtype

dtype('int8')

In [9]:
t5 = np.array([1,1,0,1,0,0], dtype=bool)
t5

array([ True,  True, False,  True, False, False])

In [10]:
t5.dtype

dtype('bool')

In [11]:
t6 = t5.astype('int8')
t6

array([1, 1, 0, 1, 0, 0], dtype=int8)

In [12]:
t6.dtype

dtype('int8')

In [13]:
import random
t7 = np.array([random.random() for i in range(10)])
t7

array([0.29648941, 0.52312121, 0.58569722, 0.38852231, 0.93923585,
       0.67463048, 0.02693962, 0.06128622, 0.10788784, 0.982483  ])

In [14]:
t7.dtype

dtype('float64')

In [15]:
t8 = np.round(t7, 2)
t8

array([0.3 , 0.52, 0.59, 0.39, 0.94, 0.67, 0.03, 0.06, 0.11, 0.98])

# 数组的维度

In [16]:
t1 = np.arange(12)
t1.shape

(12,)

In [17]:
t2 = np.array([[1,2,3],
               [4,5,6]])
t2.shape

(2, 3)

In [18]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
t3.shape

(2, 2, 3)

In [20]:
t4 = np.arange(12)
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
t4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
t5 = np.arange(24).reshape((2,3,4))
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
t5 = t5.reshape(4,6)

In [24]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
t5.reshape((24,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
t5.reshape((1,24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
t6 = t5.reshape((t5.shape[0]*t5.shape[1],))
t6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

维度展开

In [28]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
t5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 广播机制

In [30]:
t5 + 2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [31]:
t5 / 0

/tmp/ipykernel_4991/265377603.py:1: RuntimeWarning: divide by zero encountered in true_divide
  t5 / 0
/tmp/ipykernel_4991/265377603.py:1: RuntimeWarning: invalid value encountered in true_divide
  t5 / 0


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [32]:
t6 = np.arange(100,124).reshape((4,6))

对应位置数值进行计算

In [33]:
t6+t5

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [34]:
t7 = np.arange(0,6)

每一行减去被减数组

In [35]:
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [36]:
t8 = np.arange(4).reshape(4,1)

每一列减去被减列

In [37]:
t5-t8

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [41]:
t9 = np.arange(10)

## 转置

In [51]:
t2 = np.arange(48).reshape(6,8) # 4行6列
t2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [52]:
t2.transpose() # 转置

array([[ 0,  8, 16, 24, 32, 40],
       [ 1,  9, 17, 25, 33, 41],
       [ 2, 10, 18, 26, 34, 42],
       [ 3, 11, 19, 27, 35, 43],
       [ 4, 12, 20, 28, 36, 44],
       [ 5, 13, 21, 29, 37, 45],
       [ 6, 14, 22, 30, 38, 46],
       [ 7, 15, 23, 31, 39, 47]])

In [53]:
t2.T # 转置

array([[ 0,  8, 16, 24, 32, 40],
       [ 1,  9, 17, 25, 33, 41],
       [ 2, 10, 18, 26, 34, 42],
       [ 3, 11, 19, 27, 35, 43],
       [ 4, 12, 20, 28, 36, 44],
       [ 5, 13, 21, 29, 37, 45],
       [ 6, 14, 22, 30, 38, 46],
       [ 7, 15, 23, 31, 39, 47]])

In [54]:
t2.swapaxes(0,1)

array([[ 0,  8, 16, 24, 32, 40],
       [ 1,  9, 17, 25, 33, 41],
       [ 2, 10, 18, 26, 34, 42],
       [ 3, 11, 19, 27, 35, 43],
       [ 4, 12, 20, 28, 36, 44],
       [ 5, 13, 21, 29, 37, 45],
       [ 6, 14, 22, 30, 38, 46],
       [ 7, 15, 23, 31, 39, 47]])

## 取行

In [55]:
t2[2] # 取第3行

array([16, 17, 18, 19, 20, 21, 22, 23])

In [56]:
t2[2:] # 取第3行之后的每一行

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [58]:
t2[[2, 3, 5]] # 取不连续多行

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

## 取列

In [59]:
t2[:,0] # 取列

array([ 0,  8, 16, 24, 32, 40])

In [60]:
t2[:,2:] # 第3列之后的所有列

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47]])

In [61]:
t2[:,[0,2,3]] # 不连续列

array([[ 0,  2,  3],
       [ 8, 10, 11],
       [16, 18, 19],
       [24, 26, 27],
       [32, 34, 35],
       [40, 42, 43]])

## 取多行多列

In [62]:
a = t2[2,3]
a

19

In [63]:
type(a)

numpy.int64

In [64]:
t2[2:5, 1:4]

array([[17, 18, 19],
       [25, 26, 27],
       [33, 34, 35]])

In [65]:
t2[[0,2,2],[0,1,3]]

array([ 0, 17, 19])

## 数值修改

In [66]:
t4 = t2
t4 = np.copy(t2)
t4 < 10

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [67]:
t4[t4<10] = 3
t4

array([[ 3,  3,  3,  3,  3,  3,  3,  3],
       [ 3,  3, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [68]:
t4[t4>20] = 20
t4

array([[ 3,  3,  3,  3,  3,  3,  3,  3],
       [ 3,  3, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20]])

In [69]:
a = 3 if 3 > 2 else 4
a

3

In [70]:
a = 3 if 3 > 4 else 4
a

4

In [71]:
t5 = np.copy(t2)
np.where(t5<10, 1, 300)

array([[  1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1, 300, 300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300, 300, 300, 300]])

In [72]:
t6 = np.copy(t2)
t6.clip(10, 300)

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [73]:
t7 = np.copy(t2)

In [74]:
t7[1,2] = np.nan

ValueError: cannot convert float NaN to integer

In [75]:
t7 = t7.astype(float)
t7[1,1] = np.nan
t7

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8., nan, 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47.]])

当读取本地文件为float时，如果有缺失，就会出现nan，或者当做了一个不合适的计算时（如inf-inf）也会出现nan

In [76]:
a = np.nan
type(a)

float

In [77]:
a = np.inf
type(a)

float

In [78]:
np.nan != np.nan # 两个nan不相等

True

In [81]:
t7[:,0] = 0
t7

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0., nan, 10., 11., 12., 13., 14., 15.],
       [ 0., 17., 18., 19., 20., 21., 22., 23.],
       [ 0., 25., 26., 27., 28., 29., 30., 31.],
       [ 0., 33., 34., 35., 36., 37., 38., 39.],
       [ 0., 41., 42., 43., 44., 45., 46., 47.]])

In [82]:
np.count_nonzero(t7) # 计算非0数值

42

In [84]:
np.count_nonzero(t7!=t7) # 计算nan的个数

1

In [86]:
np.isnan(t7)

array([[False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [91]:
np.count_nonzero(np.isnan)

1

nan和任何数计算都是nan

In [93]:
np.sum(t7)

nan

In [95]:
t8 = np.arange(12).reshape(3,4)
t8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.sum(t8)

66

In [98]:
np.sum(t8, axis=0)

array([12, 15, 18, 21])

axis=0压成一行，axis=1压成一列

In [99]:
np.sum(t8, axis=1)

array([ 6, 22, 38])

In [100]:
np.sum(t7, axis=0)

array([  0.,  nan, 132., 138., 144., 150., 156., 162.])

In [101]:
np.sum(t7, axis=1)

array([ 28.,  nan, 140., 196., 252., 308.])

### 缺失的值(nan)替换为均值或中值

In [103]:
t7.mean(axis=0)

array([ 0., nan, 22., 23., 24., 25., 26., 27.])

In [105]:
np.median(t7)

nan

In [106]:
np.median(t7, axis=0)

array([ 0., nan, 22., 23., 24., 25., 26., 27.])

In [107]:
t7.max(axis=0)

array([ 0., nan, 42., 43., 44., 45., 46., 47.])

In [108]:
t7.min(axis=0)

array([ 0., nan,  2.,  3.,  4.,  5.,  6.,  7.])

In [167]:
np.ptp(t7, axis=0)

array([ 0., nan, 40., 40., 40., 40., 40., 40.])

## 数组拼接

In [169]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [171]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [176]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
t = np.eye(4)
t

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [180]:
t.argmax(axis=0) # 返回最大值的位置

array([0, 1, 2, 3])

In [182]:
t[t>0] = -1
t

array([[-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [186]:
np.argmin(t, axis=1)

array([0, 1, 2, 3])

## 随机数

In [189]:
np.random.randint(10,20,(4,5))

array([[15, 16, 11, 14, 19],
       [10, 19, 18, 12, 11],
       [17, 15, 10, 15, 14],
       [12, 12, 11, 15, 18]])

## copy

a = b 复制，ab之间会相互影响，浅拷贝
a = b[:] 复制，ab之间也是相互影响，浅拷贝
a = b.copy() 复制，ab之间互不影响，深拷贝